fix: block mfxxx.start/stop/status/init calls from a plugin_env
Close #112

diff --git a/adm2/templates/mfxxx.init b/adm2/templates/mfxxx.init
--- a/adm2/templates/mfxxx.init
+++ b/adm2/templates/mfxxx.init
@@ -10,6 +10,11 @@ if test "${1}" = "soft"; then
     SOFT_STRING="SOFT "
 fi
 
+PLUGIN_NAME=$(env |grep ^{{MODULE}}_CURRENT_PLUGIN_NAME |awk -F '=' '{print $2;}')
+if test "${PLUGIN_NAME}" != ""; then
+    echo "ERROR: you can't use {{MODULE_LOWERCASE}}.init inside a plugin_env"
+    exit 1
+fi
 if test "$1" != "QUIET"; then
     LINE="*****     ${MODULE} ${SOFT_STRING}INITIALIZATION     *****"
     N=`echo "${LINE}" |wc -c`
